### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by danielkucera** [OpenIPC/mini#2]
Very interresting project. Can you please add a short readme how to compile, run, used toolchain, etc.?

**Comment by ZigFisher** [comment]
All info here http://openipc.org
Build script here https://github.com/ZigFisher/Glutinium/tree/master/minihttp
Repo here https://github.com/ZigFisher/chaos_calmer

**Comment by danielkucera** [comment]
Thank you! Do you know the latency of mjpeg stream with this server?

**Comment by ZigFisher** [comment]
Depends on the size of the image from the sensor and on the processor. 
In any case, no more than a second, and often less.

**Comment by ystinia** [comment]
Non actual
